docs/source/reference/JSON-oxauth-prop.md
docs/source/reference/oxauth-config-json.json

oxAuth related issue: GluuFederation/oxAuth#1252

Added flag to toggle default code flow behaviour

---

docs/source/developer-guide/tips-cust-script-pages.md

Fixed dead link for code reference for class UserService in Developer Guide > Coding custom scripts and pages

Fixed dead link in Coding custom scripts and pages

---

docs/source/authn-guide/passport.md

https://github.com/GluuFederation/gluu-passport/issues/139

Added configuration details about new rate-limiting feature in gluu-passport

---

docs/source/installation-guide/index.md

Added 'If the status is found to be inactive, run the `ufw enable` command.'

Updated Ports section

---

docs/source/admin-guide/oxtrust-ui.md

Changed 'https://<hostname>/identity/register' into 'https://<hostname>/identity/register.htm'

Changed section Manage Registration

---

docs/source/user-management/user-registration.md

Changed 'https://<hostname>/identity/register' into 'https://<hostname>/identity/register.htm'

Updated Enable User Registration

---

docs/source/user-management/scim2.md

Current code results in the response 400 (the user is not created), and the reason for that is wrong format of the provided email address.
Changed 'email.setValue("a@b.com");' into 'email.setValue("atesting@btesting.com");'

Updated User Object

---

docs/source/user-management/scim2.md

Added 'If you get an error message 'The import of org.junit cannot be resolved', right-click on your Java project Build Path->Configure Build Path->Add Library->Junit.'

Updated Delete a User

---

docs/source/user-management/scim2.md

Added 'If the code throws an exception at readEntity method, make sure that the scim service is active by using 'service scim status' inside the Gluu container.'

Updated Simple Retrieval

---

docs/source/admin-guide/openid-connect.md

Gasmyr said that this section is not needed here anymore (as it is done during client creation).

Removed Add Sector Identifier section

---

docs/source/authn-guide/passport.md
docs/source/operation/faq.md
docs/source/tutorials/passport-inbound-flow.md
docs/source/user-management/scim2.md

fixed #75 for Passport, SCIM, CASA, and SAML.

docs: updated post setup method

---

docs/source/admin-guide/attribute.md

This PR contains docs that show adding custom attributes to Gluu ldap CN / CE setup.

Ldap addition of custom attributes 

---

docs/source/admin-guide/certificate.md

Add valid-to parameter to web, oxd, ldap, passport, scim e.g "--opts", "valid-to:365"

 Add valid-to option 

---

docs/source/admin-guide/certificate.md

Add a note for rotating in multi cluster setup

Add a note for rotating in multi cluster setup 4.3

---

docs/source/installation-guide/cluster.md

ci: dsjavaproperties no longer exists, removed.

ci: dsjavaproperties no longer exists, removed.

---

docs/source/tutorials/passport-attributes-mapping.md

Updated the Passport debugging and logging instructions

docs(passport): update and add print log section

---

docs/source/installation-guide/install-centos.md
docs/source/installation-guide/install-rhel.md
docs/source/installation-guide/install-suse.md
docs/source/installation-guide/install-ubuntu.md

Added header to linux distro installation doc as discussed [here on chat](https://chat.gluu.org/group/documentation?msg=QQNPrhrxh7WSJPC4t)

docs: add header to linux documents

---

docs/source/installation-guide/install-kubernetes.md

docs: cn docker creds 4.5

---

docs/source/release-notes/index.md

Update Release Note

---

docs/source/release-notes/index.md

(doc): Update release note

---

docs/source/release-notes/index.md

Added 4.5.3 fixed and enhancements

Added 4.5.3 fixed and enhancements

---

docs/mkdocs.yml
docs/source/integration/saas/azure.md
docs/source/upgrade/ldap-migration.md

4.2 to 4.5 ldap tp postgres migration in a kubernetes setup

docs: 4.2 to 4.5 ldap to postgres migration

---

docs/source/release-notes/index.md

Addresses the missing 4.5.4 release notes

Release notes 4.5.4
